# Generated by Django 4.2.7 on 2023-12-01 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trueque_web_service', '0002_alter_trade_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trueque_web_service.trade')),
            ],
            options={
                'unique_together': {('custom_user', 'trade')},
            },
        ),
    ]
